spring:
    jpa:
      database: mysql
    datasource:
      url: jdbc:mysql://localhost:3306/attendanceSystem 
      username: root
      password: hurezyo2
      driverClassName: com.mysql.cj.jdbc.Driver
